[workspace]
resolver = "2"
members = [
    "crates/buffer",
    "crates/doc",
    "crates/fs",
    "crates/highlight",
    "crates/format",
    "crates/plugins",
    "crates/app",
]

[workspace.package]
version = "0.2.13"
edition = "2021"
license = "MIT"

[workspace.dependencies]
ropey = "1.6"
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
format = { path = "crates/format" }
highlight = { path = "crates/highlight" }
plugins = { path = "crates/plugins" }
